### ISSUE TITLE
Please publish updated package on OPAM

### ISSUE THREAD

**Issue by reubenrowe** [ppedrot/ocaml-melt#2]
Can you please publish an updated package on OPAM, because the version there is very old: it still depends on cairo, which is now broken, so no one can install it.

**Comment by ppedrot** [comment]
I am not supposed to be a maintainer in any official way, but in the absence of anybody else I can indeed do that.

**Comment by reubenrowe** [comment]
Ah, I did not realise that you were not the maintainer! Do ignore this then if you so wish :-)
